### ISSUE TITLE
Password alert extension not working

### ISSUE THREAD

**Issue by shhnjk** [google/password-alert#106]
I installed Password Alert extension to Chrome and tried to test if Password Alert triggers warning. I've tested on https://test.shhnjk.com/login.html and several real websites. But no warning triggered. How does it protect Gmail password???

**Comment by blueandgold** [comment]
Thanks for reporting this.  After you installed the extension, were you able to  re-login to gmail, so that the extension will pickup your password?

Can you please verify what version of the extension, chrome, and OS, that you are using?

**Comment by shhnjk** [comment]
Oh, okay. I've logged out and re-logged in, and it worked now! Thanks!

**Comment by blueandgold** [comment]
Awesome, glad this is resolved.  If you have any other issues or feedbacks, please let us know.
