### ISSUE TITLE
help ?

### ISSUE THREAD

**Issue by v4nkuz** [google/password-alert#113]
{"message": "\u0418\u0437\u0447\u0430\u043a\u0430\u0439\u0442\u0435 \u043d\u044f\u043a\u043e\u043b\u043a\u043e \u043c\u0438\u043d\u0443\u0442\u0438, \u043f\u0440\u0435\u0434\u0438 \u0434\u0430 \u043f\u0440\u043e\u0431\u0432\u0430\u0442\u0435 \u043e\u0442\u043d\u043e\u0432\u043e.", "status": "fail"}

**Comment by adhintz** [comment]
Sorry, I do not understand what you are requesting help with. If you would still like help, please explain what you are doing and what error is occurring.
