### ISSUE TITLE
403 Error when sending alert to server

### ISSUE THREAD

**Issue by gnichol** [google/password-alert#84]
Hi All, 

We have implemented password alert for a small subset of users, however it doesn't show the alert screen when the user types in their password on a non-whitelisted page, and it also doesn't update the server. The console shows the below error after attempting to send the alert to the server:

POST https://########.appspot.com/report/password/ 403 (OK)
(anonymous function) @ background_compiled.js:50
target.(anonymous function) @ extensions::SafeBuiltins:19
safeCallbackApply @ extensions::sendRequest:21
handleResponse @ extensions::sendRequest:72

Any help would be greatly appreciated.

Thanks

**Comment by blueandgold** [comment]
Hi gnichol,

As a first step, can you check the appengine server log and see if there are any specific messages there?  Because there is a user_authorization_required decorator on the /report/password/ post request, which if failed will throw the 403 and will be logged.

https://github.com/google/password-alert/blob/master/server/report.py#L51

https://github.com/google/password-alert/blob/master/server/auth.py#L83

Please let me know.

**Comment by gnichol** [comment]
Looks like we are getting "Email *****@domain.com in request does not match domain None in config.py."

Thanks

**Comment by blueandgold** [comment]
It looks like no domain is configured in the settings page.  Can you please double-check that "Domain Name(s)" field is entered with your domain?

**Comment by gnichol** [comment]
Hi Henry,

Which settings page is this?

Thanks for your help


Gareth Nichol* |* Senior System Engineer
Cordant Group PLC

7-9 Swallow St
London
W1B 4DE

*p.** |* 0870 3830943
*m.** | *07760 618 563
*w.** | www.cordantgroup.com <http://www.cordantgroup.com>*



<https://www.linkedin.com/company/cordantgroup>
<https://plus.google.com/u/0/b/100348415599954999471/100348415599954999471/about>
   <https://www.facebook.com/pages/Cordant-Group-PLC/1463260903921743>

On 4 November 2015 at 23:37, Henry Chang <notifications@github.com> wrote:

> It looks like no domain is configured in the settings page. Can you please
> double-check that "Domain Name(s)" field is entered with your domain?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/password-alert/issues/84#issuecomment-153905095>
> .
>

-- 


The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

Cordant Group PLC (Recruitment Division). 346 Long Lane, Hillingdon, Middlesex, UB10 9PF.
Cordant Group PLC. is a company registered in England and Wales with company registration number: 3385619.

**Comment by blueandgold** [comment]
There is a dropdown menu on every page in the top-left corner.  Below is an
example screenshot.  I also highlighted the domain field, but you should
also look at the other fields to see if they are relevant to configure.

http://prntscr.com/8zcm35

Thanks, and please let me know if this resolves the issue.

**Comment by blueandgold** [comment]
I will consider this to be resolved.  If there's any further issues, please feel free to follow up.  Thanks.
