### ISSUE TITLE
https://mail.google.com/mail/u/0/#inbox blocked?

### ISSUE THREAD

**Issue by tbakrf** [google/password-alert#86]
We just got our first false positive on https://mail.google.com/mail/u/0/#inbox 
I know the agent is granular but a lot of folks would naturally go through Gmail, no?
Should this remain unknown by default or whitelisted?
(I set it to allow on our end for now to avoid throwing the warning email for users)

thanks!

**Comment by jkosslyn** [comment]
Thanks for the report! Can you clarify the end-user experience here? It sounds like someone typed their password into a draft email and the alert triggered; if so, that's likely working as intended since you don't want users emailing their passwords to anyone.

**Comment by tbakrf** [comment]
Veeeery interesting.  If that's the actual trigger, that's amazing / great
you've captured it!
I'm investigating now, stand by.

**Comment by tbakrf** [comment]
Sorry for the delay - this was definitely what happened.  We've removed the whitelist on our end so we can capture this in the future.  No one should be emailing their password. This is great. Thanks!
