### ISSUE TITLE
Password registered even after wrong password was used.

### ISSUE THREAD

**Issue by nloomans** [google/password-alert#92]
When you install the extension and it asks you to sign in to your google account, it will save the first password you entered even if the password you entered was incorrect.

**Comment by adhintz** [comment]
Thanks for the report. Are you using the version from the Chrome Web Store,
or a version you built from source?

**Comment by nloomans** [comment]
Chrome Web Store, I am going to test the GitHub version right now.

**Comment by adhintz** [comment]
Thanks for the reply. Are you testing with a consumer account (gmail.com) or a Google for Work account (your own domain name)? 

I have a couple changes I need to push out to github that deal with the accounts.google.com sign-in URLs.

**Comment by nloomans** [comment]
gmail, but I do have a Google for Education account (as a student) that I can test with.

**Comment by nloomans** [comment]
Sorry that I ask it here, but building the extension isn't working for me...
```
$ ./do.sh install_deps
Installing build dependencies...
Cloning into 'closure-library'...
remote: Counting objects: 2682, done.
remote: Compressing objects: 100% (2130/2130), done.
remote: Total 2682 (delta 853), reused 846 (delta 525), pack-reused 0
Receiving objects: 100% (2682/2682), 4.97 MiB | 1.01 MiB/s, done.
Resolving deltas: 100% (853/853), done.
Checking connectivity... done.
Cloning into 'closure-compiler'...
remote: Counting objects: 1596, done.
remote: Compressing objects: 100% (1329/1329), done.
remote: Total 1596 (delta 507), reused 597 (delta 233), pack-reused 0
Receiving objects: 100% (1596/1596), 8.04 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (507/507), done.
Checking connectivity... done.
Checking out files: 100% (1490/1490), done.
Buildfile: /home/cyborg/Code/password-alert/chrome/lib/closure-compiler/build.xml

relversion:

compile:
=== A lot of of java warnings === 

jar:
      [jar] Building jar: /home/cyborg/Code/password-alert/chrome/lib/closure-compiler/build/compiler.jar

BUILD SUCCESSFUL
Total time: 51 seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  232k  100  232k    0     0   200k      0  0:00:01  0:00:01 --:--:--  200k
Done.

$ ./do.sh build_extension
All dependencies met.
Building extension to build/extension
Compiling JS files...
.ERROR - Duplicate input: lib/closure-library/closure/goog/deps.js

1 error(s), 0 warning(s)
```

Did I do something wrong, or should I create an issue? (my OS is elementary OS, witch is Ubuntu based.)

**Comment by eewayhsu** [comment]
I was having the same issues and opened a ticket [here](https://github.com/google/password-alert/issues/93).  I made some tweaks that have gotten it built, but there are still some issues on top of th.  At least from the testing I've done so far!

**Comment by adhintz** [comment]
Thanks for the report. This is now fixed by https://github.com/google/password-alert/pull/96/commits/7a3bb30871689477d269f947f3b3753272331b35

This fix is not yet pushed to the Chrome Web Store.
