### ISSUE TITLE
Tests can't be run. 

### ISSUE THREAD

**Issue by eewayhsu** [google/password-alert#95]
Tests for background.js and content_script.js are broken because resources aren't found from incorrect paths.

**Comment by adhintz** [comment]
Sorry about that. The paths are for our internal test system. There's currently no way to run the tests on the open source code.

do.sh has some references to testserver copied from @google/end-to-end   However it doesn't actually work on @google/password-alert If I get some extra time, I'll try porting over the testserver to run on password-alert

**Comment by adhintz** [comment]
Fixed by #97

To run the tests:
./do.sh testserver
Then open your web browser to http://127.0.0.1:8000 and click on the test file to run.
The tests are quite useful for development as you can use the Chrome JavaScript debugger to put breakpoints during tests and inspect state.
